"""Add device name and description

Revision ID: 098bef417a7e
Revises: d7f536f95eb7
Create Date: 2026-02-17 16:23:02.163483
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098bef417a7e'
down_revision: Union[str, None] = 'd7f536f95eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('name', sa.String(length=200), nullable=True))
    op.add_column('device', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'description')
    op.drop_column('device', 'name')
    # ### end Alembic commands ###
