"""Add device security fields

Revision ID: d7f536f95eb7
Revises: 0001_greenminddb_v2
Create Date: 2026-02-17 16:21:35.942941
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f536f95eb7'
down_revision: Union[str, None] = '0001_greenminddb_v2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('device')]

    if 'api_key_hash' not in columns:
        op.add_column('device', sa.Column('api_key_hash', sa.String(length=200), nullable=True))
    if 'api_key_last_rotated_at' not in columns:
        op.add_column('device', sa.Column('api_key_last_rotated_at', sa.DateTime(timezone=True), nullable=True))
    if 'is_active' not in columns:
        op.add_column('device', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))

    # Skipping index changes to avoid conflicts with existing schema state
    # op.drop_index('ix_annotation_gh', table_name='annotation')
    # ... (omitted for safety)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_plant_signal_1hz_sensor_id'), table_name='plant_signal_1hz')
    op.drop_index(op.f('ix_plant_signal_1hz_plant_id'), table_name='plant_signal_1hz')
    op.drop_index(op.f('ix_plant_signal_1hz_greenhouse_id'), table_name='plant_signal_1hz')
    op.create_index('plant_signal_1hz_time_idx', 'plant_signal_1hz', [sa.text('time DESC')], unique=False)
    op.create_index('ix_signal_sensor_time', 'plant_signal_1hz', ['sensor_id', sa.text('time DESC')], unique=False)
    op.create_index('ix_signal_plant_time', 'plant_signal_1hz', ['plant_id', sa.text('time DESC')], unique=False)
    op.create_index('ix_signal_gh_time', 'plant_signal_1hz', ['greenhouse_id', sa.text('time DESC')], unique=False)
    op.drop_index(op.f('ix_object_meta_time'), table_name='object_meta')
    op.drop_index(op.f('ix_object_meta_greenhouse_id'), table_name='object_meta')
    op.create_index('ix_objmeta_gh_time', 'object_meta', ['greenhouse_id', 'time'], unique=False)
    op.drop_index(op.f('ix_lab_results_plant_id'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_greenhouse_id'), table_name='lab_results')
    op.drop_index(op.f('ix_ground_truth_daily_plant_id'), table_name='ground_truth_daily')
    op.drop_index(op.f('ix_ground_truth_daily_greenhouse_id'), table_name='ground_truth_daily')
    op.create_index('ix_gt_plant', 'ground_truth_daily', ['plant_id'], unique=False)
    op.create_index('ix_gt_gh', 'ground_truth_daily', ['greenhouse_id'], unique=False)
    op.drop_index(op.f('ix_export_job_greenhouse_id'), table_name='export_job')
    op.drop_index(op.f('ix_event_log_type'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_time'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_greenhouse_id'), table_name='event_log')
    op.create_index('ix_event_type', 'event_log', ['type'], unique=False)
    op.create_index('ix_event_gh_time', 'event_log', ['greenhouse_id', 'time'], unique=False)
    op.drop_index(op.f('ix_env_measurement_sensor_id'), table_name='env_measurement')
    op.drop_index(op.f('ix_env_measurement_greenhouse_id'), table_name='env_measurement')
    op.create_index('ix_env_sensor_time', 'env_measurement', ['sensor_id', sa.text('time DESC')], unique=False)
    op.create_index('ix_env_gh_time', 'env_measurement', ['greenhouse_id', sa.text('time DESC')], unique=False)
    op.create_index('env_measurement_time_idx', 'env_measurement', [sa.text('time DESC')], unique=False)
    op.drop_column('device', 'is_active')
    op.drop_column('device', 'api_key_last_rotated_at')
    op.drop_column('device', 'api_key_hash')
    op.drop_index(op.f('ix_audit_log_time'), table_name='audit_log')
    op.create_index('ix_audit_time', 'audit_log', ['time'], unique=False)
    op.drop_index(op.f('ix_annotation_review_annotation_id'), table_name='annotation_review')
    op.create_index('ix_annrev_annotation', 'annotation_review', ['annotation_id'], unique=False)
    op.drop_index(op.f('ix_annotation_plant_id'), table_name='annotation')
    op.drop_index(op.f('ix_annotation_greenhouse_id'), table_name='annotation')
    op.create_index('ix_annotation_plant', 'annotation', ['plant_id'], unique=False)
    op.create_index('ix_annotation_gh', 'annotation', ['greenhouse_id'], unique=False)
    # ### end Alembic commands ###
