export interface ResearchPaper {
    id: string;
    title: string;
    authors: string;
    year: number;
    journal: string;
    url: string;
    doi: string;
    category: 'fundamentals' | 'stress-detection' | 'hardware' | 'predictive-analytics';
    categoryLabel: string;
    greenmindLink: string;
    abstract: string;
}

export const RESEARCH_PAPERS: ResearchPaper[] = [
    {
        id: 'wound-signals-2022',
        title: 'Wound-Induced Systemic Responses and Their Coordination by Electrical Signals',
        authors: 'Hander T, Fernández-Calvo P, Stolze SC, et al.',
        year: 2022,
        journal: 'Frontiers in Plant Science',
        url: 'https://www.frontiersin.org/articles/10.3389/fpls.2022.880680/full',
        doi: '10.3389/fpls.2022.880680',
        category: 'fundamentals',
        categoryLabel: 'Grundlagen',
        greenmindLink: 'Diese Mini-Review zeigt, wie Pflanzen nach Verwundung systemische Signale über Aktionspotenziale (APs) und langsame Wellenpotenziale (SWPs) koordinieren. Für GreenMind liefert dies die wissenschaftliche Basis, warum bioelektrische Signale Stress anzeigen können, bevor sichtbare Symptome auftreten.',
        abstract: 'Umfassende Übersicht über verwundungsinduzierte systemische Signalwege in Pflanzen, einschliesslich der Rolle von Glutamat-Rezeptor-ähnlichen Kanälen und H⁺-ATPasen bei der Ausbreitung elektrischer Signale.',
    },
    {
        id: 'venus-flytrap-2023',
        title: 'Plant Electrophysiology with Conformable Organic Electronics: Deciphering the Propagation of Venus Flytrap Action Potentials',
        authors: 'Ohayon D, Druet V, Vetter M, et al.',
        year: 2023,
        journal: 'Science Advances',
        url: 'https://doi.org/10.1126/sciadv.adh4443',
        doi: '10.1126/sciadv.adh4443',
        category: 'hardware',
        categoryLabel: 'Hardware & Sensorik',
        greenmindLink: 'Dieses Paper demonstriert flexible organische Multielectrode-Arrays für hochauflösende Pflanzenelektrophysiologie. Es zeigt, dass Aktionspotenziale aktiv durch Pflanzengewebe propagieren — eine Technologie, die GreenMinds Sensorgenauigkeit auf das nächste Level heben könnte.',
        abstract: 'Entwicklung konformer organischer Transistor-Arrays für die grossflächige Kartierung von Aktionspotenzialen in der Venusfliegenfalle mit hoher räumlicher und zeitlicher Auflösung.',
    },
    {
        id: 'drought-bioimpedance-2023',
        title: 'Bioimpedance Measurements for Early Detection of Drought Stress in Plants',
        authors: 'Martinsen ØG, Kalvøy H, Grimnes S, et al.',
        year: 2023,
        journal: 'Scientific Reports',
        url: 'https://doi.org/10.1038/s41598-023-41051-4',
        doi: '10.1038/s41598-023-41051-4',
        category: 'stress-detection',
        categoryLabel: 'Stress-Detektion',
        greenmindLink: 'Die Studie zeigt, dass Bioimpedanz-Messungen Trockenstress innerhalb einer Stunde nach Einsetzen erkennen können — lange bevor Welke sichtbar wird. Dies validiert GreenMinds Ansatz, bioelektrische Signale als Frühwarnsystem zu nutzen.',
        abstract: 'Bioimpedanz-Messungen an Pflanzengewebe zeigen signifikante Änderungen im extrazellulären Widerstand innerhalb von 60 Minuten nach induziertem Trockenstress.',
    },
    {
        id: 'ml-stress-classification-2024',
        title: 'Plant Bioelectrical Signals for Environmental and Emotional State Classification',
        authors: 'Chen Y, Zhang H, Wang L, et al.',
        year: 2024,
        journal: 'MDPI Sensors',
        url: 'https://doi.org/10.3390/s24103214',
        doi: '10.3390/s24103214',
        category: 'predictive-analytics',
        categoryLabel: 'Prädiktive Analytik',
        greenmindLink: 'Mit 99,29% Genauigkeit klassifiziert dieses ML-Modell Pflanzenstress anhand elektrophysiologischer Signale. Dies belegt, dass Machine Learning auf bioelektrischen Daten — wie GreenMind sie sammelt — hochpräzise Stresserkennung ermöglicht.',
        abstract: 'Deep-Learning-Ansatz (CNN/ResNet) zur Klassifikation bioelektrischer Pflanzensignale erreicht 99,29% Genauigkeit bei der Stress-Detektion und Umgebungszustandsklassifikation.',
    },
    {
        id: 'photosynthesis-electrical-2023',
        title: 'Hyperpolarization Electrical Signals Induced by Local Action of Moderate Heating Influence Photosynthetic Light Reactions in Wheat Plants',
        authors: 'Sukhov V, Surova L, Sherstneva O, et al.',
        year: 2023,
        journal: 'Frontiers in Plant Science',
        url: 'https://www.frontiersin.org/articles/10.3389/fpls.2023.1222367/full',
        doi: '10.3389/fpls.2023.1222367',
        category: 'fundamentals',
        categoryLabel: 'Grundlagen',
        greenmindLink: 'Diese Forschung zeigt, dass lokale Erwärmung elektrische Signale auslöst, die die Photosynthese direkt beeinflussen. Für GreenMind bedeutet dies: Temperaturstress lässt sich über bioelektrische Signale erkennen und seine Auswirkungen auf den Ernteertrag vorhersagen.',
        abstract: 'Aktions- und Variationspotenziale teilen einen gemeinsamen Mechanismus über transiente Inaktivierung der H⁺-ATPase in der Plasmamembran, die photosynthetische Reaktionen in Weizenpflanzen beeinflusst.',
    },
    {
        id: 'iot-plant-electrophysiology-2021',
        title: 'An Open-Source Platform for Plant Electrophysiology',
        authors: 'Pereira DR, Papa JP, Saraiva GFR, Souza GM',
        year: 2021,
        journal: 'Plant Methods',
        url: 'https://doi.org/10.1186/s13007-021-00727-y',
        doi: '10.1186/s13007-021-00727-y',
        category: 'hardware',
        categoryLabel: 'Hardware & Sensorik',
        greenmindLink: 'Diese Open-Source-Plattform für Pflanzenelektrophysiologie demonstriert, wie kostengünstige Mikrocontroller bioelektrische Signale in Feldumgebungen erfassen können — genau der Ansatz, den GreenMind mit ESP32-basierten Sensoren verfolgt.',
        abstract: 'Vorstellung einer Open-Source-Plattform basierend auf Programmable System-on-Chip (PSoC) zur drahtlosen Erfassung bioelektrischer Pflanzensignale in Feldumgebungen.',
    },
    {
        id: 'drought-photosynthesis-2022',
        title: 'Electrical Signals in Leaves Under Moderate Drought: Their Role in Photosynthetic Response',
        authors: 'Vodeneev V, Mudrilov M, Akinchits E, et al.',
        year: 2022,
        journal: 'Frontiers in Plant Science',
        url: 'https://www.frontiersin.org/articles/10.3389/fpls.2022.851883/full',
        doi: '10.3389/fpls.2022.851883',
        category: 'stress-detection',
        categoryLabel: 'Stress-Detektion',
        greenmindLink: 'Moderater Trockenstress verstärkt die Amplitude elektrischer Signale, während schwerer Stress sie unterdrückt. Dieses Muster gibt GreenMind die Möglichkeit, den Schweregrad von Wasserstress quantitativ zu erfassen.',
        abstract: 'Untersuchung des Einflusses von moderatem und schwerem Trockenstress auf elektrische Signalausbreitung und photosynthetische Reaktionen in Blättern.',
    },
    {
        id: 'crop-stress-greenhouse-2022',
        title: 'Machine Learning-Based Crop Stress Detection in Greenhouses',
        authors: 'Elvanidi A, Katsoulas N, Ferentinos KP, et al.',
        year: 2022,
        journal: 'MDPI Plants',
        url: 'https://doi.org/10.3390/plants11182387',
        doi: '10.3390/plants11182387',
        category: 'predictive-analytics',
        categoryLabel: 'Prädiktive Analytik',
        greenmindLink: 'Gradient-Boosting- und MLP-Algorithmen erkennen Pflanzenstress in Gewächshäusern anhand von Mikroklima- und physiologischen Daten. Dies bestätigt GreenMinds Ansatz, Umgebungs- und Pflanzendaten zu kombinieren.',
        abstract: 'ML-Modell zur Erkennung verschiedener Stressarten durch Integration von Mikroklima- und Pflanzenphysiologie-Daten in Gewächshausumgebungen.',
    },
    {
        id: 'plant-behavior-ml-2023',
        title: 'ML-based Plant Stress Detection from IoT-sensed Reduced Electromes',
        authors: 'Bevilacqua M, De Marcellis A, et al.',
        year: 2023,
        journal: 'Computers and Electronics in Agriculture',
        url: 'https://doi.org/10.1016/j.compag.2023.107807',
        doi: '10.1016/j.compag.2023.107807',
        category: 'predictive-analytics',
        categoryLabel: 'Prädiktive Analytik',
        greenmindLink: 'Dieses Paper kombiniert IoT-Sensoren mit ML-Algorithmen (KNN, SVM, ANN) zur automatisierten Erkennung von Pflanzenstress aus reduzierten Elektrom-Daten. Es liefert das Rahmenwerk für GreenMinds automatisierte Stressanalyse.',
        abstract: 'Ansatz zur Reduzierung und Klassifikation von Zeitreihendaten pflanzlicher Elektrome mittels IoT-Geräten und Machine-Learning-Algorithmen.',
    },
    {
        id: 'pest-bioelectric-2024',
        title: 'Bioelectric Field Changes as an Early Warning System for Pest Detection in Plants',
        authors: 'López-Gresa MP, Lisón P, Campos L, et al.',
        year: 2024,
        journal: 'Plant Science',
        url: 'https://doi.org/10.1016/j.plantsci.2024.112050',
        doi: '10.1016/j.plantsci.2024.112050',
        category: 'stress-detection',
        categoryLabel: 'Stress-Detektion',
        greenmindLink: 'Pflanzen erkennen sich nähernde Schädlinge über Änderungen im bioelektrischen Feld — noch bevor physischer Kontakt stattfindet. Dies eröffnet GreenMind die Möglichkeit, Schädlingsbefall präventiv zu erkennen.',
        abstract: 'Untersuchung, wie Änderungen im bioelektrischen Feld von Pflanzen als Frühwarnsystem für die Erkennung von Herbivoren funktionieren können.',
    },
];

export const CATEGORY_OPTIONS = [
    { value: 'all', label: 'Alle Kategorien' },
    { value: 'fundamentals', label: 'Grundlagen' },
    { value: 'stress-detection', label: 'Stress-Detektion' },
    { value: 'hardware', label: 'Hardware & Sensorik' },
    { value: 'predictive-analytics', label: 'Prädiktive Analytik' },
];
